### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jcolomb** [open-make/AIRtrack-rebuilt#8]
- [x] Go over lab, see how things are connected to frame (pictures)
- [x] Check bar size with tool, ask for replacement of the bad component.
- [x] Bigger angles for table frame
- [x] Discuss with Mik a 3d print solution
- [x] Work on website: think 2 versions (size) of table - complex project
- [x] Ask workshop for component list + CAD files
- [x] camera fixation: directly on frame? (what distance should it be?)

**Comment by jcolomb** [comment]
open connectors with power to get it working with slightly too big bars.
